name: Auto commit
on:
  
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: |
         git config --global user.email "azizmaziz666@gmail.com"
         git config --global user.name "azizmaziz666"
         while :; do git commit -am tod --allow-empty; git push -u origin main; sleep 3600; done
